### ISSUE TITLE
Usa hooks wn

### ISSUE THREAD

**Issue by lMumen** [MissunderstoodKnight/proyecto-react#7]
Cachai que aprendi a usar hooks y estan la zorra, podrias buscar y ver que onda, basicamente dejai de usar el componente como clase y lo construyes como funcion, y con eso podi hacer weas mas bakanosas.
como que hay una wea que se llama useEffect igual que junta como el componentDidMount, componentWillUnmount, componentDidUpdate en una pura wea y es mas comodo. hechale un ojuelo jejeje

https://reactjs.org/docs/hooks-intro.html
https://reactjs.org/docs/hooks-state.html
https://reactjs.org/docs/hooks-effect.html

**Comment by MissunderstoodKnight** [comment]
Estoy usando hooks, o los empecé a usar en un proyecto que aún no subo.
Está wea está deprecada y la hice antes de que se incorporen los hooks

**Comment by lMumen** [comment]
a ya muy bn, tkm sube la otra wea pa sapearla

**Comment by MissunderstoodKnight** [comment]
Por qué no me hablas por ig xdddd. La otra wea está en stand by. Me dió un
bajoneo anímico de septiembre y me quiero pegar tremendo balazo pero cuando
se me pase continuaré el otro uwu
